name: Test matrix with choice

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ['a1', 'a2']
        bar: ['b1', 'b2']
        baz: ['c1', 'c2']
    
    steps:
      - name: test
        run: |
            echo "testing choice"
            if [[ ${{ inputs.choice }} == "foo" ]]; then
              echo "${{ matrix.foo }}"
            fi
            if [[ ${{ inputs.choice }} == "bar" ]]; then
              echo "${{ matrix.bar }}"
            fi
            if [[ ${{ inputs.choice }} == "baz" ]]; then
              echo "${{ matrix.baz }}"
            fi
