name: Test matrix with choice

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - choice: foo
            cluster1: 'a1'
            cluter2: 'a2'
          - choice: bar
            cluster1: 'b1'
            cluter2: 'b2'
          - choice: baz
            cluster1: 'c1'
            cluter2: 'c2'
    
    steps:
      - name: test
        run: |
            echo "testing choice"
            if [[ ${{ inputs.choice }} == "foo" ]]; then
              echo "${{ matrix.foo }}"
            fi
            if [[ ${{ inputs.choice }} == "bar" ]]; then
              echo "${{ matrix.bar }}"
            fi
            if [[ ${{ inputs.choice }} == "baz" ]]; then
              echo "${{ matrix.baz }}"
            fi
