name: Test matrix with choice

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar


jobs:
  job:
   runs-on: ubuntu-latest
   if: github.event.inputs.choice == 'foo'
   strategy:
      matrix:
        choice: ['foo1', 'foo2']
        
   steps:
    - name: test
      run: |
            echo "testing matrix"
            echo "${{ matrix.choice }}"
  job2:
   runs-on: ubuntu-latest
   if: github.event.inputs.choice == 'bar'
   strategy:
      matrix:
        choice: ['bar1', 'bar2']
        
   steps:
    - name: test
      run: |
            echo "testing matrix"
            echo "${{ matrix.choice }}"
            
