name: Test matrix with choice

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: test
        run: |
            echo "testing choice"
            if [[ ${{ inputs.choice }} == "foo" ]]; then
              echo "choose foo"
            fi
            if [[ ${{ inputs.choice }} == "bar" ]]; then
              echo "choose bar"
            fi
            if [[ ${{ inputs.choice }} == "baz" ]]; then
              echo "choose baz"
            fi
