name: Test matrix

on:
  workflow_dispatch:
    inputs:
      test_names:
        description: 'names'
        default: '[""]'


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_names: ${{ fromJSON(github.event.inputs.test_names)}
    
    steps:
      - name: test
        run: |
            echo "testing matrix"
            echo "${{ matrix.test_names }}"
